Psalm mentions that \PhpParser\Node\Stmt\ClassLike::$name defined as ?\PhpParser\Node\Identifier, so it is set (not null), it is never not \PhpParser\Node\Identifier. Which makes the instanceof check always true.
ERROR: RedundantCondition - src/AstUtils.php:48:21 - Type PhpParser\Node\Identifier for $current->name is always PhpParser\Node\Identifier (see https://psalm.dev/122)
                if (isset($current->name) && $current->name instanceof Node\Identifier) {